---
format:
  html: default
title: 1 Homework

---


:::{.callout-warning}
1) how to add benchmark to repo pull request to where  - add benchmark to docs?
1) how to ask questions on writing benchmark, discussion goes where (Canvas?)
1) how to write blog on what got done
1) how to submit blog url to canvas, what do they submit for grading

:::



Your goal is to get familiar with Bril.

Part 1

Write a new benchmark.

You can write it by hand, use the TypeScript compiler, or generate it some other way.
Try running it with brili.

Open a pull request to add your new benchmark.  ??? 
Add your code to the the benchmarks directory.

Use turnt --save yours.bril to create the test outputs for your new benchmark. (See the Turnt README for details.)
Mention it in the docs.

part 2
Write a program to analyze or transform Bril programs in some small way.
Pick your favorite programming language—there is no "starter code," so you can start from scratch.

Load up a JSON file. You can start with this tiny one!
Read the docs.

Do something unambitious with it: count the number of add instructions, or add a print instruction before every jump, or whatever. Pick something small and contrived!
Use Turnt to test your new tool.

Along the way, you will run into problems! Ask questions on ???, and open issues and pull requests to describe or fix problems. For example, even super simple benchmarks you might imagine probably can't be written easily because Bril is too simple. Mention this on  ??? discussions, and consider pitching in to help add features.

 Think about how to write a good test, and
finally write a post describing your work and submit it in Canvas





