---
format:
  html: default
title: homework 0

---


Write a paragraph to introduce yourself in a reply to the canvas introductions topic.  Add a picture of you can.
Mention a compilers topic you’d like to learn about someday, either in this class or beyond. Add your info to the canvas introductions discussion topic. 

Pick a paper from the [weekly schedule](../weekly.qmd) whose discussion you will lead. Claim the paper by opening a pull request (at the class github) for the weekly.qmd file, fill in your name in the LEADER: line. 

Add a text file containing done to Canvas assignment 0 to indicate you have done the introduction and claimed a paper 

1. For this  assignment you just need to submit a response to the canvas assignment to indicate that you are done after you write your introduction into canvas 
1. For other assignments you should: 

    1. Write a blog post describing your work, and submit it via a pull request to the github page
    2. Add a response to the the canvas assignment giving the name of your blog post 


My plan is that grades, personal details and the like stay in canvas and everything else becomes public and goes on the github website.





