---
title: "Schedule"
format: html
---

:::{.callout-caution}
Where do we  discussions

This actually the syllabus - needs weekly dates for a schedule, and paper list 

we also need to get the notebooks to show up in  the lectures section
:::


| Week | Topic | lectures| Discussion|
| ---- | ----- |---|---|
| 1    | Compiler overview and structure |[lecture](../lectures/010_compiler_overview.qmd)      | ???| 
 |     | Performance Measurement         |[lecture](../lectures/02a_performance_measurement.qmd)|???|
| 2    | Representing programs           |[lecture](../lectures/02b_representation.ipynb)       |???|
|      | Overview of Bril                |[notebook](../notebooks/bril.ipynb)               |???   |
| 3    | Local analysis and optimization |[lecture](../lectures/03_local.qmd)       |???   |
| 4    | Data flow                       |[lecture](../lectures/04_data_flow.qmd)|???            |
| 5    | Global analysis                 |[lecture](../lectures/05_global.qmd)|???            |
| 6    | Static single assignment        |[lecture](../lectures/06_ssa.qmd)|???            |
| 7    | LLVM                            |[lecture](../notebooks/llvm.ipynb)|???            |
| 8    | Classical loop optimizations    |[lecture](../lectures/08_loops.qmd)|???            |
| 9    | Polyhedral analysis             |[lecture](../lectures/09_poly.qmd)|???            |
| 10   | MLIR                            |[lecture](../lectures/10_mlir.qmd)|???            |
| 11   | Interprocedural Analysis        |[lecture](../lectures/11_whole_program.qmd)|???            |
| 12   | Memory Management               |[lecture](../lectures/12_memory.qmd)|???            |
| 13   | Dynamic compilers               |[lecture](../lectures/13_dynamic_compilers.qmd)|???            |
| 14   | GPU Compilers                   |[lecture](../lectures/14_gpu_compilers.qmd)|???            |


Papers 

:::{.callout-caution}
list of papers and dates for student presentations 
:::